### ISSUE TITLE
Reformat season in uptake data objects

### ISSUE THREAD

**Issue by eschrom** [CDCgov/cfa-immunization-uptake-projection#29]
Season should include both the fall and spring years (for overwinter seasons, that is). E.g. "2024/25" not "2024"
Also, consider making season something that the data must already contain upon retrieving, rather than manipulated in the code.

**Comment by swo** [comment]
Hopefully "season" will be unambiguous for the things we're dealing with. CDC defines "season" differently for different pathogens and surveillance systems (including some that have an interseason period).

For something like season flu and COVID vaccinations we should be able to do something simple that is unambiguous
