### ISSUE TITLE
Lumping vs. splitting of model objects

### ISSUE THREAD

**Issue by eschrom** [CDCgov/cfa-immunization-uptake-projection#31]
Right now, a model object contains many attributes: the model structure itself, the fit parameters, some initial conditions for projections, the incident and cumulative projections the fit model implies, etc. Instead of lumping all this information into one model object, should we split the model object into a hierarchy of distinct objects? Consider which schemes would be most efficient in terms of passing information around and not redoing calculations unnecessarily.

**Comment by eschrom** [comment]
See PR#72

**Comment by swo** [comment]
Resolves #72
