### ISSUE TITLE
Consistent method of enforcing polars subclass

### ISSUE THREAD

**Issue by eschrom** [CDCgov/cfa-immunization-uptake-projection#42]
Subclasses of a polars data frame (any UptakeData, e.g.) will revert to regular polars data frame after a polars operation (e.g. filter, with_columns, rename, etc.). We can make versions of these polars functions that return the subclass they were given, or we can coerce polars data frames into subclasses more frequently (i.e. UptakeData(df)). Choose a strategy and be consistent.

**Comment by swo** [comment]
I lean toward option #2 (let data frames be data frames, and use the subclasses for explicit validation or when we need extra functionality)

**Comment by eschrom** [comment]
Also, make choose class vs. object methods carefully to avoid self = self.some_method(...), as is currently the case in `augment_implicit_columns`

**Comment by swo** [comment]
> Also, make choose class vs. object methods carefully to avoid self = self.some_method(...), as is currently the case in `augment_implicit_columns`

Or, at least, keep something like that as an object method, but make it not modify-in-place. Eg `my_df = my_df.augment()` rather than `my_df.augment()` changing the content of `my_df`.

**Comment by swo** [comment]
this was resolved in a prior PR, maybe #65
