### ISSUE TITLE
Add validation to eval joins

### ISSUE THREAD

**Issue by swo** [CDCgov/cfa-immunization-uptake-projection#46]
Yes. The rows that has the mutual `date` between `data_df` and `pred_df` will be selected.

_Originally posted by @Fuhan-Yang in https://github.com/CDCgov/cfa-immunization-uptake-projection/pull/37#discussion_r1829929015_

**Comment by Fuhan-Yang** [comment]
Solved in [PR#52](https://github.com/CDCgov/cfa-immunization-uptake-projection/pull/52/commits)
