### ISSUE TITLE
Create end-of-season absolute error metric

### ISSUE THREAD

**Issue by swo** [CDCgov/cfa-immunization-uptake-projection#47]
Sounds good. In next PR incorporating the OOP, I will add the absolute error relative to the observed end-of-season uptake: like abs(data-predicted)/data to see how deviated the prediction is compared to the data.

_Originally posted by @Fuhan-Yang in https://github.com/CDCgov/cfa-immunization-uptake-projection/pull/37#discussion_r1830017226_

**Comment by Fuhan-Yang** [comment]
Solved in [PR#52](https://github.com/CDCgov/cfa-immunization-uptake-projection/pull/52/commits)
