### ISSUE TITLE
Consolidate `iup/*.py` files

### ISSUE THREAD

**Issue by Fuhan-Yang** [CDCgov/cfa-immunization-uptake-projection#57]
Perhaps we should insist that `data_df` and `pred_df` are IncidentUptakeData polars dataframes, specifically.

_Originally posted by @eschrom in https://github.com/CDCgov/cfa-immunization-uptake-projection/pull/52#discussion_r1838376259_

 We can consider to delete the function files in the `iup` where the functions have been used in `__init__.py`.

**Comment by eschrom** [comment]
I am ready to delete all files except `__init__.py` from the iup folder. @Fuhan-Yang feel free to delete when you are ready!
