### ISSUE TITLE
Validate using `isinstance`, not casting

### ISSUE THREAD

**Issue by swo** [CDCgov/cfa-immunization-uptake-projection#71]
fair, maybe this should be `isinstance(data, IncidentUptakeData)`?

_Originally posted by @swo in https://github.com/CDCgov/cfa-immunization-uptake-projection/pull/69#discussion_r1869705579_

**Comment by Fuhan-Yang** [comment]
Resolved in #73.

**Comment by Fuhan-Yang** [comment]
Resolved in #73.
