### ISSUE TITLE
Add gitignore

### ISSUE THREAD

**Issue by swo** [CDCgov/cfa-immunization-uptake-projection#8]
If we're going to end up using python, use this one: https://github.com/github/gitignore/blob/main/Python.gitignore

**Comment by Fuhan-Yang** [comment]
This is addressed in the [commit](https://github.com/CDCgov/cfa-immunization-uptake-projection/pull/10/commits/102e472e981a10494f057b2e030e6f6f886ffcf4) under the #10 PR.
